title: Curso QGIS
description: Repositório de dados do curso
show_downloads: true
github:
  zip_url: https://github.com/geosaber/dados/tree/master/download.zip
  another_url: https://github.com/geosaber/dados/tree/master/download.tar.gz
google_analytics:
theme: jekyll-theme-tactile
