title: Curso QGIS
description: Repositório de dados do curso
show_downloads: true
github:
  zip_url: https://github.com/geosaber/dados/zipball/master
  tar_url: https://github.com/geosaber/dados/tarball/master
google_analytics:
theme: jekyll-theme-tactile
